set_property SRC_FILE_INFO {cfile:{C:/HLS_Design/Microblaze_UART_Vitis/Microblaze_UART_Vitis.srcs/constrs_1/imports/HLS_Design/Nexys 4.xdc} rfile:{../../../Microblaze_UART_Vitis.srcs/constrs_1/imports/HLS_Design/Nexys 4.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports reset]
set_property src_info {type:XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports usb_uart_rxd]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports usb_uart_txd]
